// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwgenfbaifviavszgwsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3Z2VuZmJhaWZ2aWF2c3pnd3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzM5NTAsImV4cCI6MjA3MTg0OTk1MH0.prfycZXp8h5fxSZtiGZZlUHjZU8VbXYazvhxcHNv9M4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});